// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddCredentials(newAuthString: string): $CancellablePromise<void> {
    return $Call.ByID(4083250689, newAuthString);
}

/**
 * AddGoogleAccount exchanges an Embedded Setup oauth_token for a Google Photos
 * credential using the GUI's proxy preference, saves it, and returns the email.
 */
export function AddGoogleAccount(oauthToken: string): $CancellablePromise<string> {
    return $Call.ByID(733209449, oauthToken);
}

export function AddSyncFolder(folder: string): $CancellablePromise<void> {
    return $Call.ByID(708177970, folder);
}

export function AddTokenBindingAliasFromADB(email: string): $CancellablePromise<void> {
    return $Call.ByID(3252041498, email);
}

/**
 * CancelInAppGoogleLogin closes the active in-app Google login window if one is open.
 */
export function CancelInAppGoogleLogin(): $CancellablePromise<void> {
    return $Call.ByID(317231242);
}

/**
 * ClearFailedQueue clears all unresolved failed items from the queue.
 */
export function ClearFailedQueue(): $CancellablePromise<void> {
    return $Call.ByID(3249450437);
}

/**
 * ClearUploadHistory removes all sessions and item records from the database.
 */
export function ClearUploadHistory(): $CancellablePromise<void> {
    return $Call.ByID(4150821354);
}

export function CredentialNeedsTokenBinding(authString: string): $CancellablePromise<boolean> {
    return $Call.ByID(920629710, authString);
}

/**
 * DismissFailedItem marks a failed item as resolved in the queue.
 */
export function DismissFailedItem(id: number): $CancellablePromise<void> {
    return $Call.ByID(2854156036, id);
}

export function GetAccounts(): $CancellablePromise<$models.AccountsState> {
    return $Call.ByID(562122970).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetAlbumAutoMode(): $CancellablePromise<boolean> {
    return $Call.ByID(492228705);
}

export function GetAlbumName(): $CancellablePromise<string> {
    return $Call.ByID(3590690922);
}

/**
 * GetAllFailedFilesForRetry returns existing on-disk paths for all unresolved failed items.
 */
export function GetAllFailedFilesForRetry(): $CancellablePromise<string[]> {
    return $Call.ByID(2198270848).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetAutoSyncStatus(): $CancellablePromise<$models.AutoSyncStatus> {
    return $Call.ByID(4136090252).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetExcludePattern(): $CancellablePromise<string> {
    return $Call.ByID(2942848526);
}

/**
 * GetFailedFilesForRetry returns existing on-disk paths for failed items in a specific session.
 */
export function GetFailedFilesForRetry(sessionID: number): $CancellablePromise<string[]> {
    return $Call.ByID(776929141, sessionID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetFailedQueue returns active unresolved failed upload items.
 */
export function GetFailedQueue(): $CancellablePromise<$models.FailedItemSummary[]> {
    return $Call.ByID(228255922).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetFolderAlbumKey(folder: string): $CancellablePromise<string> {
    return $Call.ByID(3651401376, folder);
}

export function GetPresetFolders(): $CancellablePromise<$models.PresetFolders> {
    return $Call.ByID(3658713694).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetSessionDetails returns the detailed information for a specific session.
 */
export function GetSessionDetails(sessionID: number): $CancellablePromise<$models.UploadSessionDetails | null> {
    return $Call.ByID(3397228188, sessionID).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetSettings(): $CancellablePromise<$models.Preferences> {
    return $Call.ByID(4262641511).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetSyncFolders(): $CancellablePromise<string[]> {
    return $Call.ByID(4187658046).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetUploadHistory retrieves paginated upload sessions from the local database.
 */
export function GetUploadHistory(limit: number, offset: number): $CancellablePromise<$models.UploadSessionSummary[]> {
    return $Call.ByID(3979600553, limit, offset).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * OpenDirectoryDialog opens the OS native directory picker dialog and returns the selected folder.
 */
export function OpenDirectoryDialog(): $CancellablePromise<string> {
    return $Call.ByID(2438934449);
}

export function RemoveCredentials(email: string): $CancellablePromise<void> {
    return $Call.ByID(4243930372, email);
}

export function RemoveSyncFolder(folder: string): $CancellablePromise<void> {
    return $Call.ByID(621066969, folder);
}

export function SetAlbumAutoMode(autoMode: boolean): $CancellablePromise<void> {
    return $Call.ByID(1935381765, autoMode);
}

export function SetAlbumName(albumName: string): $CancellablePromise<void> {
    return $Call.ByID(841849854, albumName);
}

/**
 * SetApp saves the Wails application reference for window management.
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(471517813, app);
}

export function SetAutoAlbumEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1240202985, enabled);
}

export function SetAutoSyncEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(203272859, enabled);
}

export function SetDeleteFromHost(deleteFromHost: boolean): $CancellablePromise<void> {
    return $Call.ByID(377345147, deleteFromHost);
}

export function SetDisableUnsupportedFilesFilter(disableUnsupportedFilesFilter: boolean): $CancellablePromise<void> {
    return $Call.ByID(821557574, disableUnsupportedFilesFilter);
}

export function SetExcludePattern(pattern: string): $CancellablePromise<void> {
    return $Call.ByID(4021766002, pattern);
}

export function SetFolderAlbumKey(folder: string, albumKey: string): $CancellablePromise<void> {
    return $Call.ByID(1023619460, folder, albumKey);
}

export function SetForceUpload(forceUpload: boolean): $CancellablePromise<void> {
    return $Call.ByID(2189240988, forceUpload);
}

export function SetMaxUploadSpeedMBps(speed: number): $CancellablePromise<void> {
    return $Call.ByID(3029183470, speed);
}

export function SetPairLivePhotos(pairLivePhotos: boolean): $CancellablePromise<void> {
    return $Call.ByID(3927958009, pairLivePhotos);
}

export function SetProxy(proxy: string): $CancellablePromise<void> {
    return $Call.ByID(2532528442, proxy);
}

export function SetRecursive(recursive: boolean): $CancellablePromise<void> {
    return $Call.ByID(455302378, recursive);
}

export function SetSaver(saver: boolean): $CancellablePromise<void> {
    return $Call.ByID(3030960747, saver);
}

export function SetSelected(email: string): $CancellablePromise<void> {
    return $Call.ByID(2816040807, email);
}

export function SetSetDateFromFilename(v: boolean): $CancellablePromise<void> {
    return $Call.ByID(1731635347, v);
}

export function SetSkipIncompleteLivePhotos(skipIncompleteLivePhotos: boolean): $CancellablePromise<void> {
    return $Call.ByID(2521603022, skipIncompleteLivePhotos);
}

export function SetSyncOnStartup(v: boolean): $CancellablePromise<void> {
    return $Call.ByID(3766804153, v);
}

export function SetUpdateExistingPhotosToLive(updateExistingPhotosToLive: boolean): $CancellablePromise<void> {
    return $Call.ByID(3038371812, updateExistingPhotosToLive);
}

export function SetUploadThreads(uploadThreads: number): $CancellablePromise<void> {
    return $Call.ByID(1692245880, uploadThreads);
}

export function SetUseQuota(useQuota: boolean): $CancellablePromise<void> {
    return $Call.ByID(778544527, useQuota);
}

/**
 * StartInAppGoogleLogin opens a dedicated in-app WebView window for Google EmbeddedSetup,
 * polls for the oauth_token cookie, automatically closes the window upon successful login,
 * and saves the new Google Photos account.
 */
export function StartInAppGoogleLogin(): $CancellablePromise<string> {
    return $Call.ByID(910831596);
}

export function TriggerSyncNow(): $CancellablePromise<void> {
    return $Call.ByID(3134080591);
}

// Private type creation functions
const $$createType0 = $models.AccountsState.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $models.AutoSyncStatus.createFrom;
const $$createType3 = $models.FailedItemSummary.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.PresetFolders.createFrom;
const $$createType6 = $models.UploadSessionDetails.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.Preferences.createFrom;
const $$createType9 = $models.UploadSessionSummary.createFrom;
const $$createType10 = $Create.Array($$createType9);
