// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddCredentials(newAuthString: string): $CancellablePromise<void> {
    return $Call.ByID(4083250689, newAuthString);
}

/**
 * AddGoogleAccount exchanges an Embedded Setup oauth_token for a Google Photos
 * credential using the GUI's proxy preference, saves it, and returns the email.
 */
export function AddGoogleAccount(oauthToken: string): $CancellablePromise<string> {
    return $Call.ByID(733209449, oauthToken);
}

/**
 * StartInAppGoogleLogin opens an in-app WebView window for Google login,
 * automatically extracts oauth_token from cookies, and completes account connection.
 */
export function StartInAppGoogleLogin(): $CancellablePromise<string> {
    return $Call.ByName("app/backend.ConfigManager.StartInAppGoogleLogin");
}

/**
 * CancelInAppGoogleLogin closes the active in-app Google login window if open.
 */
export function CancelInAppGoogleLogin(): $CancellablePromise<void> {
    return $Call.ByName("app/backend.ConfigManager.CancelInAppGoogleLogin");
}

export function AddTokenBindingAliasFromADB(email: string): $CancellablePromise<void> {
    return $Call.ByID(3252041498, email);
}

export function CredentialNeedsTokenBinding(authString: string): $CancellablePromise<boolean> {
    return $Call.ByID(920629710, authString);
}

export function GetAccounts(): $CancellablePromise<$models.AccountsState> {
    return $Call.ByID(562122970).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetAlbumAutoMode(): $CancellablePromise<boolean> {
    return $Call.ByID(492228705);
}

export function GetAlbumName(): $CancellablePromise<string> {
    return $Call.ByID(3590690922);
}

export function GetExcludePattern(): $CancellablePromise<string> {
    return $Call.ByID(2942848526);
}

export function GetSettings(): $CancellablePromise<$models.Preferences> {
    return $Call.ByID(4262641511).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RemoveCredentials(email: string): $CancellablePromise<void> {
    return $Call.ByID(4243930372, email);
}

export function SetAlbumAutoMode(autoMode: boolean): $CancellablePromise<void> {
    return $Call.ByID(1935381765, autoMode);
}

export function SetAlbumName(albumName: string): $CancellablePromise<void> {
    return $Call.ByID(841849854, albumName);
}

export function SetDeleteFromHost(deleteFromHost: boolean): $CancellablePromise<void> {
    return $Call.ByID(377345147, deleteFromHost);
}

export function SetDisableUnsupportedFilesFilter(disableUnsupportedFilesFilter: boolean): $CancellablePromise<void> {
    return $Call.ByID(821557574, disableUnsupportedFilesFilter);
}

export function SetExcludePattern(pattern: string): $CancellablePromise<void> {
    return $Call.ByID(4021766002, pattern);
}

export function SetForceUpload(forceUpload: boolean): $CancellablePromise<void> {
    return $Call.ByID(2189240988, forceUpload);
}

export function SetPairLivePhotos(pairLivePhotos: boolean): $CancellablePromise<void> {
    return $Call.ByID(3927958009, pairLivePhotos);
}

export function SetProxy(proxy: string): $CancellablePromise<void> {
    return $Call.ByID(2532528442, proxy);
}

export function SetRecursive(recursive: boolean): $CancellablePromise<void> {
    return $Call.ByID(455302378, recursive);
}

export function SetSaver(saver: boolean): $CancellablePromise<void> {
    return $Call.ByID(3030960747, saver);
}

export function SetSelected(email: string): $CancellablePromise<void> {
    return $Call.ByID(2816040807, email);
}

export function SetSetDateFromFilename(v: boolean): $CancellablePromise<void> {
    return $Call.ByID(1731635347, v);
}

export function SetSkipIncompleteLivePhotos(skipIncompleteLivePhotos: boolean): $CancellablePromise<void> {
    return $Call.ByID(2521603022, skipIncompleteLivePhotos);
}

export function SetUpdateExistingPhotosToLive(updateExistingPhotosToLive: boolean): $CancellablePromise<void> {
    return $Call.ByID(3038371812, updateExistingPhotosToLive);
}

export function SetUploadThreads(uploadThreads: number): $CancellablePromise<void> {
    return $Call.ByID(1692245880, uploadThreads);
}

export function SetUseQuota(useQuota: boolean): $CancellablePromise<void> {
    return $Call.ByID(778544527, useQuota);
}

// Private type creation functions
const $$createType0 = $models.AccountsState.createFrom;
const $$createType1 = $models.Preferences.createFrom;
