// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AccountSummary {
    "email": string;
    "needsTokenBinding": boolean;

    /** Creates a new AccountSummary instance. */
    constructor($$source: Partial<AccountSummary> = {}) {
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("needsTokenBinding" in $$source)) {
            this["needsTokenBinding"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): AccountSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountSummary($$parsedSource as Partial<AccountSummary>);
    }
}

export class AccountsState {
    "accounts": AccountSummary[];
    "selected": string;

    /** Creates a new AccountsState instance. */
    constructor($$source: Partial<AccountsState> = {}) {
        if (!("accounts" in $$source)) {
            this["accounts"] = [];
        }
        if (!("selected" in $$source)) {
            this["selected"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountsState instance from a string or object.
     */
    static createFrom($$source: any = {}): AccountsState {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("accounts" in $$parsedSource) {
            $$parsedSource["accounts"] = $$createField0_0($$parsedSource["accounts"]);
        }
        return new AccountsState($$parsedSource as Partial<AccountsState>);
    }
}

/**
 * AlbumError represents an album creation error
 */
export class AlbumError {
    "AlbumName": string;
    "Error": string;

    /** Creates a new AlbumError instance. */
    constructor($$source: Partial<AlbumError> = {}) {
        if (!("AlbumName" in $$source)) {
            this["AlbumName"] = "";
        }
        if (!("Error" in $$source)) {
            this["Error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlbumError instance from a string or object.
     */
    static createFrom($$source: any = {}): AlbumError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AlbumError($$parsedSource as Partial<AlbumError>);
    }
}

/**
 * AlbumStatus represents the status of album creation
 */
export class AlbumStatus {
    "AlbumName": string;
    "ItemsAdded": number;
    "TotalItems": number;
    "AlbumKeys": string[];
    "IsComplete": boolean;

    /** Creates a new AlbumStatus instance. */
    constructor($$source: Partial<AlbumStatus> = {}) {
        if (!("AlbumName" in $$source)) {
            this["AlbumName"] = "";
        }
        if (!("ItemsAdded" in $$source)) {
            this["ItemsAdded"] = 0;
        }
        if (!("TotalItems" in $$source)) {
            this["TotalItems"] = 0;
        }
        if (!("AlbumKeys" in $$source)) {
            this["AlbumKeys"] = [];
        }
        if (!("IsComplete" in $$source)) {
            this["IsComplete"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlbumStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): AlbumStatus {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("AlbumKeys" in $$parsedSource) {
            $$parsedSource["AlbumKeys"] = $$createField3_0($$parsedSource["AlbumKeys"]);
        }
        return new AlbumStatus($$parsedSource as Partial<AlbumStatus>);
    }
}

/**
 * AutoSyncFileEvent is emitted when a file has been successfully uploaded via Auto-Sync.
 */
export class AutoSyncFileEvent {
    "path": string;
    "fileName": string;
    "size": number;

    /** Creates a new AutoSyncFileEvent instance. */
    constructor($$source: Partial<AutoSyncFileEvent> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutoSyncFileEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): AutoSyncFileEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AutoSyncFileEvent($$parsedSource as Partial<AutoSyncFileEvent>);
    }
}

export class AutoSyncStatus {
    "enabled": boolean;
    "isSyncing": boolean;
    "folderCount": number;
    "watchedFolders": string[];
    "queueCount": number;
    "syncedCount": number;
    "lastSyncTime": number;
    "currentFile": string;
    "statusMessage": string;

    /** Creates a new AutoSyncStatus instance. */
    constructor($$source: Partial<AutoSyncStatus> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("isSyncing" in $$source)) {
            this["isSyncing"] = false;
        }
        if (!("folderCount" in $$source)) {
            this["folderCount"] = 0;
        }
        if (!("watchedFolders" in $$source)) {
            this["watchedFolders"] = [];
        }
        if (!("queueCount" in $$source)) {
            this["queueCount"] = 0;
        }
        if (!("syncedCount" in $$source)) {
            this["syncedCount"] = 0;
        }
        if (!("lastSyncTime" in $$source)) {
            this["lastSyncTime"] = 0;
        }
        if (!("currentFile" in $$source)) {
            this["currentFile"] = "";
        }
        if (!("statusMessage" in $$source)) {
            this["statusMessage"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutoSyncStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): AutoSyncStatus {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("watchedFolders" in $$parsedSource) {
            $$parsedSource["watchedFolders"] = $$createField3_0($$parsedSource["watchedFolders"]);
        }
        return new AutoSyncStatus($$parsedSource as Partial<AutoSyncStatus>);
    }
}

/**
 * FailedItemSummary represents an active failed file in the queue.
 */
export class FailedItemSummary {
    "id": number;
    "sessionId": number;
    "filePath": string;
    "fileName": string;
    "fileSize": number;
    "errorMessage": string;
    "createdAt": number;

    /** Creates a new FailedItemSummary instance. */
    constructor($$source: Partial<FailedItemSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = 0;
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("fileSize" in $$source)) {
            this["fileSize"] = 0;
        }
        if (!("errorMessage" in $$source)) {
            this["errorMessage"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FailedItemSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): FailedItemSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FailedItemSummary($$parsedSource as Partial<FailedItemSummary>);
    }
}

export class FileUploadResult {
    "MediaKey": string;
    "IsError": boolean;
    "IsLivePhoto": boolean;
    "Skipped": boolean;
    "SkipCode": string;
    "SkipReason": string;
    "ErrorMessage": string;
    "Path": string;
    "Paths": string[];

    /** Creates a new FileUploadResult instance. */
    constructor($$source: Partial<FileUploadResult> = {}) {
        if (!("MediaKey" in $$source)) {
            this["MediaKey"] = "";
        }
        if (!("IsError" in $$source)) {
            this["IsError"] = false;
        }
        if (!("IsLivePhoto" in $$source)) {
            this["IsLivePhoto"] = false;
        }
        if (!("Skipped" in $$source)) {
            this["Skipped"] = false;
        }
        if (!("SkipCode" in $$source)) {
            this["SkipCode"] = "";
        }
        if (!("SkipReason" in $$source)) {
            this["SkipReason"] = "";
        }
        if (!("ErrorMessage" in $$source)) {
            this["ErrorMessage"] = "";
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Paths" in $$source)) {
            this["Paths"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileUploadResult instance from a string or object.
     */
    static createFrom($$source: any = {}): FileUploadResult {
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Paths" in $$parsedSource) {
            $$parsedSource["Paths"] = $$createField8_0($$parsedSource["Paths"]);
        }
        return new FileUploadResult($$parsedSource as Partial<FileUploadResult>);
    }
}

/**
 * FilesDroppedEvent is emitted when files are dropped on any drop zone
 */
export class FilesDroppedEvent {
    "files": string[];
    "dropZone": string;

    /** Creates a new FilesDroppedEvent instance. */
    constructor($$source: Partial<FilesDroppedEvent> = {}) {
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("dropZone" in $$source)) {
            this["dropZone"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilesDroppedEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): FilesDroppedEvent {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField0_0($$parsedSource["files"]);
        }
        return new FilesDroppedEvent($$parsedSource as Partial<FilesDroppedEvent>);
    }
}

/**
 * Preferences are GUI settings. The CLI never reads them; every CLI run is
 * configured by flags alone.
 */
export class Preferences {
    "proxy": string;
    "useQuota": boolean;
    "saver": boolean;
    "recursive": boolean;
    "forceUpload": boolean;
    "pairLivePhotos": boolean;
    "skipIncompleteLivePhotos": boolean;
    "updateExistingPhotosToLive": boolean;
    "uploadThreads": number;
    "maxUploadSpeedMBps": number;
    "deleteFromHost": boolean;
    "disableUnsupportedFilesFilter": boolean;
    "setDateFromFilename": boolean;
    "excludePattern": string;
    "autoSyncEnabled": boolean;
    "autoAlbumEnabled": boolean;
    "syncFolders": string[];
    "folderAlbums": { [_ in string]?: string };
    "syncOnStartup": boolean;

    /**
     * AlbumName and AlbumAutoMode are per-session choices and are never persisted.
     */
    "albumName": string;
    "albumAutoMode": boolean;

    /** Creates a new Preferences instance. */
    constructor($$source: Partial<Preferences> = {}) {
        if (!("proxy" in $$source)) {
            this["proxy"] = "";
        }
        if (!("useQuota" in $$source)) {
            this["useQuota"] = false;
        }
        if (!("saver" in $$source)) {
            this["saver"] = false;
        }
        if (!("recursive" in $$source)) {
            this["recursive"] = false;
        }
        if (!("forceUpload" in $$source)) {
            this["forceUpload"] = false;
        }
        if (!("pairLivePhotos" in $$source)) {
            this["pairLivePhotos"] = false;
        }
        if (!("skipIncompleteLivePhotos" in $$source)) {
            this["skipIncompleteLivePhotos"] = false;
        }
        if (!("updateExistingPhotosToLive" in $$source)) {
            this["updateExistingPhotosToLive"] = false;
        }
        if (!("uploadThreads" in $$source)) {
            this["uploadThreads"] = 0;
        }
        if (!("maxUploadSpeedMBps" in $$source)) {
            this["maxUploadSpeedMBps"] = 0;
        }
        if (!("deleteFromHost" in $$source)) {
            this["deleteFromHost"] = false;
        }
        if (!("disableUnsupportedFilesFilter" in $$source)) {
            this["disableUnsupportedFilesFilter"] = false;
        }
        if (!("setDateFromFilename" in $$source)) {
            this["setDateFromFilename"] = false;
        }
        if (!("excludePattern" in $$source)) {
            this["excludePattern"] = "";
        }
        if (!("autoSyncEnabled" in $$source)) {
            this["autoSyncEnabled"] = false;
        }
        if (!("autoAlbumEnabled" in $$source)) {
            this["autoAlbumEnabled"] = false;
        }
        if (!("syncFolders" in $$source)) {
            this["syncFolders"] = [];
        }
        if (!("folderAlbums" in $$source)) {
            this["folderAlbums"] = {};
        }
        if (!("syncOnStartup" in $$source)) {
            this["syncOnStartup"] = false;
        }
        if (!("albumName" in $$source)) {
            this["albumName"] = "";
        }
        if (!("albumAutoMode" in $$source)) {
            this["albumAutoMode"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preferences instance from a string or object.
     */
    static createFrom($$source: any = {}): Preferences {
        const $$createField16_0 = $$createType2;
        const $$createField17_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("syncFolders" in $$parsedSource) {
            $$parsedSource["syncFolders"] = $$createField16_0($$parsedSource["syncFolders"]);
        }
        if ("folderAlbums" in $$parsedSource) {
            $$parsedSource["folderAlbums"] = $$createField17_0($$parsedSource["folderAlbums"]);
        }
        return new Preferences($$parsedSource as Partial<Preferences>);
    }
}

export class PreflightWarning {
    "Paths": string[];
    "Code": string;
    "Message": string;

    /** Creates a new PreflightWarning instance. */
    constructor($$source: Partial<PreflightWarning> = {}) {
        if (!("Paths" in $$source)) {
            this["Paths"] = [];
        }
        if (!("Code" in $$source)) {
            this["Code"] = "";
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreflightWarning instance from a string or object.
     */
    static createFrom($$source: any = {}): PreflightWarning {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Paths" in $$parsedSource) {
            $$parsedSource["Paths"] = $$createField0_0($$parsedSource["Paths"]);
        }
        return new PreflightWarning($$parsedSource as Partial<PreflightWarning>);
    }
}

export class PresetFolders {
    "pictures": string;
    "downloads": string;

    /** Creates a new PresetFolders instance. */
    constructor($$source: Partial<PresetFolders> = {}) {
        if (!("pictures" in $$source)) {
            this["pictures"] = "";
        }
        if (!("downloads" in $$source)) {
            this["downloads"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PresetFolders instance from a string or object.
     */
    static createFrom($$source: any = {}): PresetFolders {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PresetFolders($$parsedSource as Partial<PresetFolders>);
    }
}

/**
 * StartUploadEvent is received from frontend to start upload
 */
export class StartUploadEvent {
    "files": string[];

    /** Creates a new StartUploadEvent instance. */
    constructor($$source: Partial<StartUploadEvent> = {}) {
        if (!("files" in $$source)) {
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartUploadEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): StartUploadEvent {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField0_0($$parsedSource["files"]);
        }
        return new StartUploadEvent($$parsedSource as Partial<StartUploadEvent>);
    }
}

export class ThreadStatus {
    "WorkerID": number;

    /**
     * "idle", "hashing", "checking", "uploading", "finalizing", "completed", "skipped", "error"
     */
    "Status": string;
    "FilePath": string;
    "FileName": string;
    "Message": string;
    "BytesUploaded": number;
    "BytesTotal": number;

    /**
     * Current attempt number (1-based), 0 if not applicable
     */
    "Attempt": number;

    /** Creates a new ThreadStatus instance. */
    constructor($$source: Partial<ThreadStatus> = {}) {
        if (!("WorkerID" in $$source)) {
            this["WorkerID"] = 0;
        }
        if (!("Status" in $$source)) {
            this["Status"] = "";
        }
        if (!("FilePath" in $$source)) {
            this["FilePath"] = "";
        }
        if (!("FileName" in $$source)) {
            this["FileName"] = "";
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }
        if (!("BytesUploaded" in $$source)) {
            this["BytesUploaded"] = 0;
        }
        if (!("BytesTotal" in $$source)) {
            this["BytesTotal"] = 0;
        }
        if (!("Attempt" in $$source)) {
            this["Attempt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreadStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ThreadStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThreadStatus($$parsedSource as Partial<ThreadStatus>);
    }
}

export class UploadBatchStart {
    "Total": number;
    "TotalBytes": number;

    /** Creates a new UploadBatchStart instance. */
    constructor($$source: Partial<UploadBatchStart> = {}) {
        if (!("Total" in $$source)) {
            this["Total"] = 0;
        }
        if (!("TotalBytes" in $$source)) {
            this["TotalBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadBatchStart instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadBatchStart {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UploadBatchStart($$parsedSource as Partial<UploadBatchStart>);
    }
}

/**
 * UploadItemRecord represents a single file entry in an upload session.
 */
export class UploadItemRecord {
    "id": number;
    "sessionId": number;
    "filePath": string;
    "fileName": string;
    "fileSize": number;

    /**
     * "success", "failed", "skipped"
     */
    "status": string;
    "errorMessage": string;
    "skipReason": string;
    "mediaKey": string;
    "resolved": boolean;
    "createdAt": number;
    "updatedAt": number;

    /** Creates a new UploadItemRecord instance. */
    constructor($$source: Partial<UploadItemRecord> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = 0;
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("fileSize" in $$source)) {
            this["fileSize"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("errorMessage" in $$source)) {
            this["errorMessage"] = "";
        }
        if (!("skipReason" in $$source)) {
            this["skipReason"] = "";
        }
        if (!("mediaKey" in $$source)) {
            this["mediaKey"] = "";
        }
        if (!("resolved" in $$source)) {
            this["resolved"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadItemRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadItemRecord {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UploadItemRecord($$parsedSource as Partial<UploadItemRecord>);
    }
}

/**
 * UploadSessionDetails holds a session summary along with all its item records.
 */
export class UploadSessionDetails {
    "session": UploadSessionSummary;
    "items": UploadItemRecord[];

    /** Creates a new UploadSessionDetails instance. */
    constructor($$source: Partial<UploadSessionDetails> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new UploadSessionSummary());
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadSessionDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadSessionDetails {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField1_0($$parsedSource["items"]);
        }
        return new UploadSessionDetails($$parsedSource as Partial<UploadSessionDetails>);
    }
}

/**
 * UploadSessionSummary represents the high-level summary of an upload session.
 */
export class UploadSessionSummary {
    "id": number;

    /**
     * "manual", "retry", "autosync"
     */
    "source": string;
    "albumName": string;
    "totalFiles": number;
    "successCount": number;
    "failedCount": number;
    "skippedCount": number;

    /**
     * "running", "completed", "cancelled", "failed"
     */
    "status": string;
    "startedAt": number;
    "endedAt": number;

    /** Creates a new UploadSessionSummary instance. */
    constructor($$source: Partial<UploadSessionSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("albumName" in $$source)) {
            this["albumName"] = "";
        }
        if (!("totalFiles" in $$source)) {
            this["totalFiles"] = 0;
        }
        if (!("successCount" in $$source)) {
            this["successCount"] = 0;
        }
        if (!("failedCount" in $$source)) {
            this["failedCount"] = 0;
        }
        if (!("skippedCount" in $$source)) {
            this["skippedCount"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = 0;
        }
        if (!("endedAt" in $$source)) {
            this["endedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadSessionSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadSessionSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UploadSessionSummary($$parsedSource as Partial<UploadSessionSummary>);
    }
}

// Private type creation functions
const $$createType0 = AccountSummary.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = UploadSessionSummary.createFrom;
const $$createType5 = UploadItemRecord.createFrom;
const $$createType6 = $Create.Array($$createType5);
