// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as backend$0 from "../../../../../app/backend/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "FileStatus": backend$0.FileUploadResult;
            "ThreadStatus": backend$0.ThreadStatus;
            "albumComplete": backend$0.AlbumStatus;
            "albumError": backend$0.AlbumError;
            "albumProgress": backend$0.AlbumStatus;
            "autosync:file-uploaded": backend$0.AutoSyncFileEvent;
            "autosync:status": backend$0.AutoSyncStatus;
            "files-dropped": backend$0.FilesDroppedEvent;
            "startUpload": backend$0.StartUploadEvent;
            "uploadCancel": void;
            "uploadPause": void;
            "uploadResume": void;
            "uploadPaused": void;
            "uploadResumed": void;
            "uploadSetBandwidthLimit": number;
            "uploadStart": backend$0.UploadBatchStart;
            "uploadStop": void;
            "uploadTotalBytes": number;
            "uploadTotalBytesDelta": number;
            "uploadWarning": backend$0.PreflightWarning;
        }
    }
}
