//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backend$0 from "../../../../../app/backend/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "FileStatus": $$createType0,
        "ThreadStatus": $$createType1,
        "albumComplete": $$createType2,
        "albumError": $$createType3,
        "albumProgress": $$createType2,
        "autosync:file-uploaded": $$createType4,
        "autosync:status": $$createType5,
        "files-dropped": $$createType6,
        "startUpload": $$createType7,
        "uploadStart": $$createType8,
        "uploadWarning": $$createType9,
    }));
}

// Private type creation functions
const $$createType0 = backend$0.FileUploadResult.createFrom;
const $$createType1 = backend$0.ThreadStatus.createFrom;
const $$createType2 = backend$0.AlbumStatus.createFrom;
const $$createType3 = backend$0.AlbumError.createFrom;
const $$createType4 = backend$0.AutoSyncFileEvent.createFrom;
const $$createType5 = backend$0.AutoSyncStatus.createFrom;
const $$createType6 = backend$0.FilesDroppedEvent.createFrom;
const $$createType7 = backend$0.StartUploadEvent.createFrom;
const $$createType8 = backend$0.UploadBatchStart.createFrom;
const $$createType9 = backend$0.PreflightWarning.createFrom;

configure();
